name: Deploy Refiner Discord Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update code and restart bot
        run: |
          cd /home/pdteggman/Code/refiner-discord-bot

          git pull origin main

          source /home/pdteggman/Code/refiner-discord-bot/refiner-venv-vps1/bin/activate
          pip install -U -r requirements.txt

          pm2 restart refiner
